const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"课后习题测试",
                        "menuJump":"列表",
                        "tableName":"chat"
                    }
                ],
                "menu":"课后习题测试"
            }
			,
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"网课信息",
                        "menuJump":"列表",
                        "tableName":"kecheng"
                    }
                ],
                "menu":"网课信息"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息"
            }
			,
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"错题本",
                        "tableName":"examrewrongquestion"
                    },
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"试卷列表",
                        "tableName":"exampaper"
                    },
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"测试记录",
                        "tableName":"examrecord"
                    }
                ],
                "menu":"测试管理"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"学生",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
